#!/usr/bin/env bash
# Auto-generated by tools/eutropy_poc/eutropy_to_estas.py -- do not hand-edit.
# CL29's flows come from EUTROPY and are NOT per-box volume-conserving, so
# ESTAS's flux-derived box volumes drain to a negative-mass crash (~day 449)
# without ESTAS_HOLD_VOLUME=1, which holds each box volume at its prescribed value.
set -euo pipefail
cd "$(dirname "$0")"                     # run from repo root regardless of CWD
if [[ ! -x ./ESTAS_II ]]; then
    echo "ESTAS_II not found -- build it first (e.g. make FC=gfortran OPENMP=1 build-estas)" >&2
    exit 1
fi
exec env ESTAS_HOLD_VOLUME=1 ./ESTAS_II "${1:-INPUT_CL29.txt}" "${@:2}"
