#!/usr/bin/env python3
"""Generate Supplementary Table S2 — per-box observation-model scores.

Reads a ``validation_metrics.csv`` written by ``validate_cl29_vs_epa.py`` and
emits the markdown table pasted into the calibration paper, so the table cannot
drift from the run that produced it (the same guarantee S1 gets from
``calibrate_cl29.py``).

The obs-weighted per-variable totals it prints as the *all boxes* rows are the
paper's Section 3.19 scorecard: pooled RMSE is sqrt(sum(n*rmse^2)/sum(n)), NOT
the mean of the per-box RMSEs.

Regenerate the input with, from the repo root::

    .venv/bin/python tools/validate_cl29_vs_epa.py \\
        --outputs OUTPUTS_CL29 --obs <epa+km concat> --base-year 2012 \\
        --wconst INPUTS_CL29/WCONST_04.txt --out <dir> --no-plots

``--wconst`` matters: chlorophyll is derived with the run's own C:Chl ratios,
which are model parameters. Scoring with the validator's module defaults instead
reports 37.97 rather than 23.83 -- a 59 % overstatement.

Group carbon (DIA_C, CYN_C, OPA_C, FIX_CYN_C, ZOO_C, PHYTO_TOT_C) only appears
if the KM plankton observations were concatenated onto the EPA tidy CSV on their
shared columns; there is no separate --plankton flag.
"""
from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from decimal import ROUND_HALF_UP, Decimal

# Display order and units, matching the Section 3.19 scorecard.
ORDER = ["NH4", "NO3", "PO4", "DO", "Si", "TN", "TP", "CHLA",
         "DIA_C", "CYN_C", "OPA_C", "FIX_CYN_C", "ZOO_C", "PHYTO_TOT_C"]
UNITS = {"NH4": "mg N L⁻¹", "NO3": "mg N L⁻¹", "PO4": "mg P L⁻¹", "DO": "mg O₂ L⁻¹",
         "Si": "mg Si L⁻¹", "TN": "mg N L⁻¹", "TP": "mg P L⁻¹", "CHLA": "µg L⁻¹"}
UNITS.update({k: "mg C L⁻¹" for k in
              ("DIA_C", "CYN_C", "OPA_C", "FIX_CYN_C", "ZOO_C", "PHYTO_TOT_C")})
# The paper reports the summed fixer pool; the validator keys it by the first.
LABEL = {"CHLA": "Chl-a", "FIX_CYN_C": "FIX_TOT_C"}
# Decimals per variable: enough to resolve the residual, no more.
DECIMALS = {"PO4": 5, "TP": 5, "NH4": 4, "CHLA": 2, "DO": 2}


def fmt(x: float, var: str) -> str:
    """Round half away from zero, not banker's.

    Python's format() rounds 0.0145 to 0.014; the paper rounded the validator's
    already-rounded 3-s.f. display up to 0.015 and so reported a ZOO_C bias one
    digit off. Quantizing the full-precision value avoids that double rounding.
    """
    places = DECIMALS.get(var, 3)
    return f"{Decimal(float(x)).quantize(Decimal(1).scaleb(-places), rounding=ROUND_HALF_UP):f}"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("metrics", help="validation_metrics.csv from validate_cl29_vs_epa.py")
    p.add_argument("--out", default=None, help="write here instead of stdout")
    args = p.parse_args(argv)

    with open(args.metrics, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    by_var = defaultdict(list)
    for r in rows:
        by_var[r["variable"]].append(r)

    unknown = sorted(set(by_var) - set(ORDER))
    if unknown:
        raise SystemExit(f"unknown variables in {args.metrics}: {unknown}")

    out = [
        "## Supplementary Table S2 — observation–model scores by model box",
        "",
        "The per-box statistics underlying the scorecard of Section 3.19 and every time-series figure.",
        "Generated by `tools/validate_cl29_vs_epa.py` from the adopted configuration's output (run of",
        "2026-09-03) with that run's own `WCONST_04.txt`, so chlorophyll is derived with the model's own",
        "C:Chl ratios rather than the validator's module defaults. The obs-weighted totals of each block",
        "reproduce the Section 3.19 scorecard exactly.",
        "",
        "Boxes are the nine carrying scored observations (Figure 1); group carbon is observed in six of",
        "them. `n` is matched observation–model pairs and `r` the Pearson correlation on those pairs; bias",
        "is model minus observation. **This table contains no individual measurements and no station",
        "identities** — it is a summary statistic of the Agency archive, not a redistribution of it.",
        "",
        "| Variable | Units | Box | n | Obs mean | Model mean | Bias | RMSE | r |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for var in ORDER:
        sub = sorted(by_var.get(var, []), key=lambda r: int(r["box"]))
        if not sub:
            continue
        label = LABEL.get(var, var)
        n_tot = sum(int(r["n"]) for r in sub)
        rmse_tot = math.sqrt(sum(int(r["n"]) * float(r["rmse"]) ** 2 for r in sub) / n_tot)
        bias_tot = sum(int(r["n"]) * float(r["bias"]) for r in sub) / n_tot
        for i, r in enumerate(sub):
            out.append(
                f"| {'**' + label + '**' if i == 0 else ''} | {UNITS[var] if i == 0 else ''} "
                f"| {int(r['box'])} | {int(r['n'])} | {fmt(r['obs_mean'], var)} "
                f"| {fmt(r['model_mean'], var)} | {fmt(r['bias'], var)} | {fmt(r['rmse'], var)} "
                f"| {float(r['r']):+.2f} |")
        out.append(f"| | *all boxes* | | **{n_tot}** | | | **{fmt(bias_tot, var)}** "
                   f"| **{fmt(rmse_tot, var)}** | |")

    text = "\n".join(out) + "\n"
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out} ({len(out)} lines)")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
