subroutine ALLELOPATHY_INHIBITION_RATES()

    use ALLELOPATHY
    implicit none


    IHBF_SEC_METAB_DIA_NOFIX_CYN     = &
        K_HS_SEC_METAB_DIA_NOFIX_CYN     / &
        (K_HS_SEC_METAB_DIA_NOFIX_CYN     + SEC_METAB_DIA      )

    IHBF_SEC_METAB_DIA_FIX_CYN       = &
        K_HS_SEC_METAB_DIA_FIX_CYN       / &
        (K_HS_SEC_METAB_DIA_FIX_CYN       + SEC_METAB_DIA      )

    IHBF_SEC_METAB_DIA_NOST          = &
        K_HS_SEC_METAB_DIA_NOST          / &
        (K_HS_SEC_METAB_DIA_NOST          + SEC_METAB_DIA      )

    IHBF_SEC_METAB_DIA_OPA           = &
        K_HS_SEC_METAB_DIA_OPA           / &
        (K_HS_SEC_METAB_DIA_OPA           + SEC_METAB_DIA      )

    IHBF_SEC_METAB_DIA_ZOO           = &
        K_HS_SEC_METAB_DIA_ZOO           / &
        (K_HS_SEC_METAB_DIA_ZOO           + SEC_METAB_DIA      )

    IHBF_SEC_METAB_NOFIX_CYN_DIA     = &
        K_HS_SEC_METAB_NOFIX_CYN_DIA     / &
        (K_HS_SEC_METAB_NOFIX_CYN_DIA     + SEC_METAB_NOFIX_CYN)

    IHBF_SEC_METAB_NOFIX_CYN_FIX_CYN = &
        K_HS_SEC_METAB_NOFIX_CYN_FIX_CYN / &
        (K_HS_SEC_METAB_NOFIX_CYN_FIX_CYN + SEC_METAB_NOFIX_CYN)

    IHBF_SEC_METAB_NOFIX_CYN_NOST    = &
        K_HS_SEC_METAB_NOFIX_CYN_NOST    / &
        (K_HS_SEC_METAB_NOFIX_CYN_NOST    + SEC_METAB_NOFIX_CYN)

    IHBF_SEC_METAB_NOFIX_CYN_OPA     = &
        K_HS_SEC_METAB_NOFIX_CYN_OPA     / &
        (K_HS_SEC_METAB_NOFIX_CYN_OPA     + SEC_METAB_NOFIX_CYN)

    IHBF_SEC_METAB_NOFIX_CYN_ZOO     = &
        K_HS_SEC_METAB_NOFIX_CYN_ZOO     / &
        (K_HS_SEC_METAB_NOFIX_CYN_ZOO     + SEC_METAB_NOFIX_CYN)

    IHBF_SEC_METAB_FIX_CYN_DIA       = &
        K_HS_SEC_METAB_FIX_CYN_DIA       / &
        (K_HS_SEC_METAB_FIX_CYN_DIA       + SEC_METAB_FIX_CYN  )

    IHBF_SEC_METAB_FIX_CYN_NOFIX_CYN = &
        K_HS_SEC_METAB_FIX_CYN_NOFIX_CYN / &
        (K_HS_SEC_METAB_FIX_CYN_NOFIX_CYN + SEC_METAB_FIX_CYN  )

    IHBF_SEC_METAB_FIX_CYN_NOST      = &
        K_HS_SEC_METAB_FIX_CYN_NOST      / &
        (K_HS_SEC_METAB_FIX_CYN_NOST      + SEC_METAB_FIX_CYN  )

    IHBF_SEC_METAB_FIX_CYN_OPA       = &
        K_HS_SEC_METAB_FIX_CYN_OPA       / &
        (K_HS_SEC_METAB_FIX_CYN_OPA       + SEC_METAB_FIX_CYN  )

    IHBF_SEC_METAB_FIX_CYN_ZOO       = &
        K_HS_SEC_METAB_FIX_CYN_ZOO       / &
        (K_HS_SEC_METAB_FIX_CYN_ZOO       + SEC_METAB_FIX_CYN  )

    IHBF_SEC_METAB_NOST_DIA          = &
        K_HS_SEC_METAB_NOST_DIA          / &
        (K_HS_SEC_METAB_NOST_DIA          + SEC_METAB_NOST     )

    IHBF_SEC_METAB_NOST_NOFIX_CYN    = &
        K_HS_SEC_METAB_NOST_NOFIX_CYN    / &
        (K_HS_SEC_METAB_NOST_NOFIX_CYN    + SEC_METAB_NOST     )

    IHBF_SEC_METAB_NOST_FIX_CYN      = &
       K_HS_SEC_METAB_NOST_FIX_CYN      / &
       (K_HS_SEC_METAB_NOST_FIX_CYN      + SEC_METAB_NOST      )

    IHBF_SEC_METAB_NOST_OPA          = &
        K_HS_SEC_METAB_NOST_OPA          / &
        (K_HS_SEC_METAB_NOST_OPA          + SEC_METAB_NOST     )

    IHBF_SEC_METAB_NOST_ZOO          = &
        K_HS_SEC_METAB_NOST_ZOO          / &
        (K_HS_SEC_METAB_NOST_ZOO          + SEC_METAB_NOST     )

    IHBF_SEC_METAB_DIA       = &
        min(IHBF_SEC_METAB_NOFIX_CYN_DIA, IHBF_SEC_METAB_FIX_CYN_DIA      , &
            IHBF_SEC_METAB_NOST_DIA      )

    IHBF_SEC_METAB_NOFIX_CYN = &
        min(IHBF_SEC_METAB_DIA_NOFIX_CYN, IHBF_SEC_METAB_FIX_CYN_NOFIX_CYN, &
            IHBF_SEC_METAB_NOST_NOFIX_CYN)

    IHBF_SEC_METAB_FIX_CYN   = &
        min(IHBF_SEC_METAB_DIA_FIX_CYN  , IHBF_SEC_METAB_NOFIX_CYN_FIX_CYN, &
            IHBF_SEC_METAB_NOST_FIX_CYN  )

    IHBF_SEC_METAB_NOST      = &
        min(IHBF_SEC_METAB_DIA_NOST     , IHBF_SEC_METAB_NOFIX_CYN_NOST   , &
            IHBF_SEC_METAB_FIX_CYN_NOST  )

    IHBF_SEC_METAB_OPA       = &
        min(IHBF_SEC_METAB_DIA_OPA      , IHBF_SEC_METAB_NOFIX_CYN_OPA    , &
           IHBF_SEC_METAB_FIX_CYN_OPA  ,  IHBF_SEC_METAB_NOST_OPA)

    IHBF_SEC_METAB_ZOO       = &
        min(IHBF_SEC_METAB_DIA_ZOO      , IHBF_SEC_METAB_NOFIX_CYN_ZOO    , &
            IHBF_SEC_METAB_FIX_CYN_ZOO  , IHBF_SEC_METAB_NOST_ZOO )

end subroutine ALLELOPATHY_INHIBITION_RATES
